const config = {
    DATE_FORMATS: [
        'MM/DD/YY',
        'DD/MM/YY',
        'YY/MM/DD',
        'Month D, Yr',
        'M/D/YY',
        'D/M/YY',
        'YY/M/D',
        'bM/bD/YY',
        'bD/bM/YY',
        'YY/bM/bD',
        'MMDDYY',
        'DDMMYY',
        'YYMMDD',
        'MonDDYY',
        'DDMonYY',
        'YYMonDD',
        'day/YY',
        'YY/day',
        'D Month, Yr',
        'Yr, Month D',
        'Mon-DD-YYYY',
        'DD-Mon-YYYY',
        'YYYYY-Mon-DD',
        'Mon DD, YYYY',
        'DD Mon, YYYY',
        'YYYY, Mon DD',
        'YYYY-MM-DD',
        'YYYY-MM',
        'YYYY',
    ],
};

export default config;